#############################################################################
# Makefile for building: PaintProgram.app/Contents/MacOS/PaintProgram
# Generated by qmake (3.1) (Qt 5.9.4)
# Project:  PaintProgram.pro
# Template: app
# Command: /Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/bin/qmake -o Makefile PaintProgram.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../Qt5.9.4/5.9.4/clang_64/lib/QtPrintSupport.framework/Headers -I../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers -I../Qt5.9.4/5.9.4/clang_64/lib/QtQuick.framework/Headers -I../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers -I../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers -I../Qt5.9.4/5.9.4/clang_64/lib/QtNetwork.framework/Headers -I../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang -F/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib
QMAKE         = /Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = PaintProgram1.0.0
DISTDIR = /Users/kendrakuivenhoven/PaintProgram/.tmp/PaintProgram1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib -framework QtPrintSupport -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtQuick -framework QtQml -framework QtNetwork -framework OpenGL -framework AGL 
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		scribblearea.cpp \
		submenu.cpp moc_mainwindow.cpp \
		moc_scribblearea.cpp \
		moc_submenu.cpp
OBJECTS       = main.o \
		mainwindow.o \
		scribblearea.o \
		submenu.o \
		moc_mainwindow.o \
		moc_scribblearea.o \
		moc_submenu.o
DIST          = ../Qt5.9.4/5.9.4/clang_64/mkspecs/features/spec_pre.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/qdevice.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/device_config.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/common/unix.conf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/common/mac.conf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/common/macx.conf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/common/sanitize.conf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/common/gcc-base.conf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/common/clang.conf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/common/clang-mac.conf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/qconfig.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt_functions.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt_config.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/spec_post.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/toolchain.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/toolchain.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/default_pre.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/resolve_config.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/default_post.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qml_debug.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/warn_on.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/resources.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/moc.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/uic.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/unix/thread.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qmake_use.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/file_copies.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/rez.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/exceptions.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/yacc.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/lex.prf \
		PaintProgram.pro mainwindow.h \
		scribblearea.h \
		submenu.h main.cpp \
		mainwindow.cpp \
		scribblearea.cpp \
		submenu.cpp
QMAKE_TARGET  = PaintProgram
DESTDIR       = 
TARGET        = PaintProgram.app/Contents/MacOS/PaintProgram

####### Custom Variables
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_VALID_ARCHS = x86_64
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d PaintProgram.app/Contents/MacOS/ || mkdir -p PaintProgram.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PaintProgram.pro ../Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang/qmake.conf ../Qt5.9.4/5.9.4/clang_64/mkspecs/features/spec_pre.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/qdevice.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/device_config.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/common/unix.conf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/common/mac.conf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/common/macx.conf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/common/sanitize.conf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/common/gcc-base.conf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/common/clang.conf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/common/clang-mac.conf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/qconfig.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt_functions.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt_config.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/spec_post.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/toolchain.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/toolchain.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/default_pre.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/resolve_config.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/default_post.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qml_debug.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/warn_on.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/resources.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/moc.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/uic.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/unix/thread.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qmake_use.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/file_copies.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/rez.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/exceptions.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/yacc.prf \
		../Qt5.9.4/5.9.4/clang_64/mkspecs/features/lex.prf \
		PaintProgram.pro \
		../Qt5.9.4/5.9.4/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQuick.framework/QtQuick.prl \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/QtGui.prl \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/QtQml.prl \
		../Qt5.9.4/5.9.4/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile PaintProgram.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/spec_pre.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/qdevice.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/device_config.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/common/unix.conf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/common/mac.conf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/common/macx.conf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/common/sanitize.conf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/common/gcc-base.conf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/common/gcc-base-mac.conf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/common/clang.conf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/common/clang-mac.conf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/qconfig.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_charts.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_core.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_help.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_location.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_network.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_script.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt_functions.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt_config.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang/qmake.conf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/spec_post.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/exclusive_builds.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/sdk.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/toolchain.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/toolchain.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/default_pre.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/default_pre.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/resolve_config.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/default_post.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/default_post.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/objective_c.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qml_debug.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/warn_on.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/resources.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/moc.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/unix/opengl.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/uic.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/unix/thread.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qmake_use.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/file_copies.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/rez.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/testcase_targets.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/exceptions.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/yacc.prf:
../Qt5.9.4/5.9.4/clang_64/mkspecs/features/lex.prf:
PaintProgram.pro:
../Qt5.9.4/5.9.4/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl:
../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../Qt5.9.4/5.9.4/clang_64/lib/QtQuick.framework/QtQuick.prl:
../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/QtGui.prl:
../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/QtQml.prl:
../Qt5.9.4/5.9.4/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile PaintProgram.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

PaintProgram.app/Contents/PkgInfo: 
	@test -d PaintProgram.app/Contents || mkdir -p PaintProgram.app/Contents
	@$(DEL_FILE) PaintProgram.app/Contents/PkgInfo
	@echo "APPL????" > PaintProgram.app/Contents/PkgInfo
PaintProgram.app/Contents/Resources/empty.lproj: 
	@test -d PaintProgram.app/Contents/Resources || mkdir -p PaintProgram.app/Contents/Resources
	@touch PaintProgram.app/Contents/Resources/empty.lproj
	
PaintProgram.app/Contents/Info.plist: 
	@test -d PaintProgram.app/Contents || mkdir -p PaintProgram.app/Contents
	@$(DEL_FILE) PaintProgram.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,aboutkendra.herokuapp.com.PaintProgram,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,PaintProgram,g" -e "s,@LIBRARY@,PaintProgram,g" -e "s,@TYPEINFO@,????,g" ../Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang/Info.plist.app >PaintProgram.app/Contents/Info.plist

all: Makefile \
		PaintProgram.app/Contents/PkgInfo \
		PaintProgram.app/Contents/Resources/empty.lproj \
		PaintProgram.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../Qt5.9.4/5.9.4/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h scribblearea.h submenu.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp scribblearea.cpp submenu.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r PaintProgram.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../Qt5.9.4/5.9.4/clang_64/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h ../Qt5.9.4/5.9.4/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_scribblearea.cpp moc_submenu.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_scribblearea.cpp moc_submenu.cpp
moc_mainwindow.cpp: ../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QList \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QColorDialog \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QImageWriter \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QMenu \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QMdiSubWindow \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQuick.framework/Headers/QQuickView \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQuick.framework/Headers/qquickview.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/QtQml \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qtqmlglobal.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qjsengine.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qjsvalue.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qjsvalueiterator.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqml.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlabstracturlinterceptor.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlcomponent.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlcontext.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmldebug.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlengine.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlerror.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlexpression.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlextensioninterface.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlextensionplugin.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlfile.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlfileselector.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlincubator.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlinfo.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmllist.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlnetworkaccessmanagerfactory.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlparserstatus.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlprivate.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlproperty.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlpropertymap.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlpropertyvaluesource.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlscriptstring.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qtqmlversion.h \
		scribblearea.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QColor \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QImage \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPoint \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QLinearGradient \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QRectF \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QRect \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPainterPath \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDir \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPair \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpair.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPointF \
		submenu.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDebug \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QStyle \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		mainwindow.h \
		moc_predefs.h \
		../Qt5.9.4/5.9.4/clang_64/bin/moc
	/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang -I/Users/kendrakuivenhoven/PaintProgram -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib/QtQuick.framework/Headers -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib/QtNetwork.framework/Headers -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_scribblearea.cpp: ../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QColor \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QImage \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPoint \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QLinearGradient \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QRectF \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QRect \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPainterPath \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDir \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPair \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpair.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QList \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPointF \
		scribblearea.h \
		moc_predefs.h \
		../Qt5.9.4/5.9.4/clang_64/bin/moc
	/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang -I/Users/kendrakuivenhoven/PaintProgram -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib/QtQuick.framework/Headers -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib/QtNetwork.framework/Headers -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib scribblearea.h -o moc_scribblearea.cpp

moc_submenu.cpp: ../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDebug \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QColor \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QColorDialog \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QStyle \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQuick.framework/Headers/QQuickView \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQuick.framework/Headers/qquickview.h \
		scribblearea.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QImage \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPoint \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QLinearGradient \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QRectF \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QRect \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPainterPath \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDir \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPair \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpair.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QList \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPointF \
		submenu.h \
		moc_predefs.h \
		../Qt5.9.4/5.9.4/clang_64/bin/moc
	/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang -I/Users/kendrakuivenhoven/PaintProgram -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib/QtQuick.framework/Headers -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib/QtNetwork.framework/Headers -I/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/lib submenu.h -o moc_submenu.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../Qt5.9.4/5.9.4/clang_64/bin/uic
	/Users/kendrakuivenhoven/Qt5.9.4/5.9.4/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QList \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QColorDialog \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QImageWriter \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QMenu \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QMdiSubWindow \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQuick.framework/Headers/QQuickView \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQuick.framework/Headers/qquickview.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/QtQml \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qtqmlglobal.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qjsengine.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qjsvalue.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qjsvalueiterator.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqml.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlabstracturlinterceptor.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlcomponent.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlcontext.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmldebug.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlengine.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlerror.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlexpression.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlextensioninterface.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlextensionplugin.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlfile.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlfileselector.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlincubator.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlinfo.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmllist.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlnetworkaccessmanagerfactory.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlparserstatus.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlprivate.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlproperty.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlpropertymap.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlpropertyvaluesource.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlscriptstring.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qtqmlversion.h \
		scribblearea.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QColor \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QImage \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPoint \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QLinearGradient \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QRectF \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QRect \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPainterPath \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDir \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPair \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpair.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPointF \
		submenu.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDebug \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QStyle \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QList \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QColorDialog \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QImageWriter \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QMenu \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QMdiSubWindow \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQuick.framework/Headers/QQuickView \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQuick.framework/Headers/qquickview.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/QtQml \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qtqmlglobal.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qjsengine.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qjsvalue.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qjsvalueiterator.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqml.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlabstracturlinterceptor.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlcomponent.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlcontext.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmldebug.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlengine.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlerror.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlexpression.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlextensioninterface.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlextensionplugin.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlfile.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlfileselector.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlincubator.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlinfo.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmllist.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlnetworkaccessmanagerfactory.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlparserstatus.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlprivate.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlproperty.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlpropertymap.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlpropertyvaluesource.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qqmlscriptstring.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQml.framework/Headers/qtqmlversion.h \
		scribblearea.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QColor \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QImage \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPoint \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QLinearGradient \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QRectF \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QRect \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPainterPath \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDir \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPair \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpair.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPointF \
		submenu.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDebug \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QStyle \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

scribblearea.o: scribblearea.cpp scribblearea.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QColor \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QImage \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPoint \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QLinearGradient \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QRectF \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QRect \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPainterPath \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDir \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPair \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpair.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QList \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPointF \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QtWidgets \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsglobal.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qabstractslider.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qcolormap.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qcolumnview.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qcompleter.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qdirmodel.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qdrawutil.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qerrormessage.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qfocusframe.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgesture.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgroupbox.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qkeyeventtransition.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qlistview.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qmdiarea.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qmouseeventtransition.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qproxystyle.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qrubberband.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qscroller.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qshortcut.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qstylefactory.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qstylepainter.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qtoolbox.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qtreeview.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qundogroup.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qundostack.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qundoview.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsversion.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtPrintSupport.framework/Headers/QPrinter \
		../Qt5.9.4/5.9.4/clang_64/lib/QtPrintSupport.framework/Headers/qprinter.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtPrintSupport.framework/Headers/QPrintDialog \
		../Qt5.9.4/5.9.4/clang_64/lib/QtPrintSupport.framework/Headers/qprintdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scribblearea.o scribblearea.cpp

submenu.o: submenu.cpp submenu.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDebug \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QColor \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QColorDialog \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QStyle \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQuick.framework/Headers/QQuickView \
		../Qt5.9.4/5.9.4/clang_64/lib/QtQuick.framework/Headers/qquickview.h \
		scribblearea.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QImage \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPoint \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QLinearGradient \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QRectF \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QRect \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPainterPath \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QDir \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPair \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpair.h \
		../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QList \
		../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPointF
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o submenu.o submenu.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_scribblearea.o: moc_scribblearea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scribblearea.o moc_scribblearea.cpp

moc_submenu.o: moc_submenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_submenu.o moc_submenu.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

